version: '3'
services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./dev/configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./application/:/var/www/html/
    links:
      - php-fpm
      - db
    networks:
      - app-network

  php-fpm:
    build: dev/context/php
    volumes:
      - ./application/:/var/www/html/:cached
    ports:
      - 9000:9000
    links:
      - db
    networks:
      - app-network

  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=refactor
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=docker
    networks:
      - app-network


networks:
  app-network:
    driver: bridge